Slim update (#160)
* chore: use latest images

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

* feat: run slim test on latest built images

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

* fix: add pod wathcer to slim deploy

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

* fix: slim image tag name

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

* feat: add Dockerfile for python bindings examples

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

* feat: use freshly build examples images for test

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

* feat: deploy chart from local repo

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

* fix: temporary disable spire and run only one node per group

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

---------

Signed-off-by: Magyari Sandor Szilard <sancyx@gmail.com>

diff --git a/.github/actions/deploy-components/action.yaml b/.github/actions/deploy-components/action.yaml
--- a/.github/actions/deploy-components/action.yaml
+++ b/.github/actions/deploy-components/action.yaml
@@ -34,7 +34,27 @@ inputs:
     required: false
     default: ''
   slim-chart-tag:
-    description: 'Set slim chart version'
+    description: 'Set slim chart version (OCI only; ignored when slim-repo-path is set)'
+    required: false
+    default: ''
+  slim-repo-path:
+    description: 'Absolute path to agntcy/slim repo root with charts/; empty uses OCI charts'
+    required: false
+    default: ''
+  slim-controller-image-tag:
+    description: 'Set slim controller container image version'
+    required: false
+    default: ''
+  preload-slim-images:
+    description: 'Load prebuilt slim images into kind'
+    required: false
+    default: 'false'
+  slim-node-image:
+    description: 'Full slim node image reference to load into kind'
+    required: false
+    default: ''
+  slim-controller-image:
+    description: 'Full slim controller image reference to load into kind'
     required: false
     default: ''
   deploy-directory:
@@ -116,6 +136,20 @@ runs:
         task -d ./${{ inputs.checkout-path }} integrations:kind:create \
           KIND_CLUSTER_NAME=${{ inputs.kind-cluster-name }}
 
+    - name: Load prebuilt slim images into kind
+      if: ${{ inputs.preload-slim-images != 'false' }}
+      shell: bash
+      run: |
+        set -euo pipefail
+
+        if [ -z "${{ inputs.slim-node-image }}" ] || [ -z "${{ inputs.slim-controller-image }}" ]; then
+          echo "Both slim-node-image and slim-controller-image are required when preload-slim-images is enabled."
+          exit 1
+        fi
+
+        kind load docker-image "${{ inputs.slim-node-image }}" --name "${{ inputs.kind-cluster-name }}"
+        kind load docker-image "${{ inputs.slim-controller-image }}" --name "${{ inputs.kind-cluster-name }}"
+
     - name: Deploy SPIRE
       if: ${{ inputs.deploy-spire != 'false' }}      
       shell: bash
@@ -127,13 +161,17 @@ runs:
       shell: bash
       run: |
         task -d ./${{ inputs.checkout-path }} integrations:slim:test-env:deploy:controller \
+          SLIM_REPO_PATH='${{ inputs.slim-repo-path }}' \
           SLIM_IMAGE_TAG=${{ inputs.slim-image-tag }} \
+          SLIM_CONTROLLER_IMAGE_TAG=${{ inputs.slim-controller-image-tag }} \
           SLIM_CHART_TAG=${{ inputs.slim-chart-tag }} \
           KIND_CLUSTER_NAME=${{ inputs.kind-cluster-name }} \
           HELM_NAMESPACE=${{ inputs.kind-cluster-namespace }}
 
         task -d ./${{ inputs.checkout-path }} integrations:slim:test-env:deploy:clusters \
+          SLIM_REPO_PATH='${{ inputs.slim-repo-path }}' \
           SLIM_IMAGE_TAG=${{ inputs.slim-image-tag }} \
+          SLIM_CONTROLLER_IMAGE_TAG=${{ inputs.slim-controller-image-tag }} \
           SLIM_CHART_TAG=${{ inputs.slim-chart-tag }} \
           KIND_CLUSTER_NAME=${{ inputs.kind-cluster-name }} \
           HELM_NAMESPACE=${{ inputs.kind-cluster-namespace }}
@@ -143,6 +181,7 @@ runs:
       shell: bash
       run: |
         task -d ./${{ inputs.checkout-path }} integrations:slim:test-env:deploy \
+          SLIM_REPO_PATH='${{ inputs.slim-repo-path }}' \
           SLIM_CONFIG=${{ inputs.slim-config }} \
           SLIM_IMAGE_TAG=${{ inputs.slim-image-tag }} \
           SLIM_CHART_TAG=${{ inputs.slim-chart-tag }} \
